/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ElectionsRouteImport } from './routes/elections'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ElectionsPositionIdRouteImport } from './routes/elections.$positionId'
import { Route as CandidatesApplyRouteImport } from './routes/candidates.apply'
import { Route as ElectionsCandidatesPositionIdRouteImport } from './routes/elections.candidates.$positionId'
import { Route as CandidatesCandidateIdDashboardRouteImport } from './routes/candidates.$candidateId.dashboard'
import { Route as CandidatesCandidateIdCertificateRouteImport } from './routes/candidates.$candidateId.certificate'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionsRoute = ElectionsRouteImport.update({
  id: '/elections',
  path: '/elections',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionsPositionIdRoute = ElectionsPositionIdRouteImport.update({
  id: '/$positionId',
  path: '/$positionId',
  getParentRoute: () => ElectionsRoute,
} as any)
const CandidatesApplyRoute = CandidatesApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => CandidatesRoute,
} as any)
const ElectionsCandidatesPositionIdRoute =
  ElectionsCandidatesPositionIdRouteImport.update({
    id: '/candidates/$positionId',
    path: '/candidates/$positionId',
    getParentRoute: () => ElectionsRoute,
  } as any)
const CandidatesCandidateIdDashboardRoute =
  CandidatesCandidateIdDashboardRouteImport.update({
    id: '/$candidateId/dashboard',
    path: '/$candidateId/dashboard',
    getParentRoute: () => CandidatesRoute,
  } as any)
const CandidatesCandidateIdCertificateRoute =
  CandidatesCandidateIdCertificateRouteImport.update({
    id: '/$candidateId/certificate',
    path: '/$candidateId/certificate',
    getParentRoute: () => CandidatesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/candidates': typeof CandidatesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/elections': typeof ElectionsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/candidates/apply': typeof CandidatesApplyRoute
  '/elections/$positionId': typeof ElectionsPositionIdRoute
  '/candidates/$candidateId/certificate': typeof CandidatesCandidateIdCertificateRoute
  '/candidates/$candidateId/dashboard': typeof CandidatesCandidateIdDashboardRoute
  '/elections/candidates/$positionId': typeof ElectionsCandidatesPositionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/candidates': typeof CandidatesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/elections': typeof ElectionsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/candidates/apply': typeof CandidatesApplyRoute
  '/elections/$positionId': typeof ElectionsPositionIdRoute
  '/candidates/$candidateId/certificate': typeof CandidatesCandidateIdCertificateRoute
  '/candidates/$candidateId/dashboard': typeof CandidatesCandidateIdDashboardRoute
  '/elections/candidates/$positionId': typeof ElectionsCandidatesPositionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/candidates': typeof CandidatesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/elections': typeof ElectionsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/candidates/apply': typeof CandidatesApplyRoute
  '/elections/$positionId': typeof ElectionsPositionIdRoute
  '/candidates/$candidateId/certificate': typeof CandidatesCandidateIdCertificateRoute
  '/candidates/$candidateId/dashboard': typeof CandidatesCandidateIdDashboardRoute
  '/elections/candidates/$positionId': typeof ElectionsCandidatesPositionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/candidates'
    | '/dashboard'
    | '/elections'
    | '/projects'
    | '/register'
    | '/sitemap.xml'
    | '/candidates/apply'
    | '/elections/$positionId'
    | '/candidates/$candidateId/certificate'
    | '/candidates/$candidateId/dashboard'
    | '/elections/candidates/$positionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/candidates'
    | '/dashboard'
    | '/elections'
    | '/projects'
    | '/register'
    | '/sitemap.xml'
    | '/candidates/apply'
    | '/elections/$positionId'
    | '/candidates/$candidateId/certificate'
    | '/candidates/$candidateId/dashboard'
    | '/elections/candidates/$positionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/candidates'
    | '/dashboard'
    | '/elections'
    | '/projects'
    | '/register'
    | '/sitemap.xml'
    | '/candidates/apply'
    | '/elections/$positionId'
    | '/candidates/$candidateId/certificate'
    | '/candidates/$candidateId/dashboard'
    | '/elections/candidates/$positionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CandidatesRoute: typeof CandidatesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ElectionsRoute: typeof ElectionsRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elections': {
      id: '/elections'
      path: '/elections'
      fullPath: '/elections'
      preLoaderRoute: typeof ElectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elections/$positionId': {
      id: '/elections/$positionId'
      path: '/$positionId'
      fullPath: '/elections/$positionId'
      preLoaderRoute: typeof ElectionsPositionIdRouteImport
      parentRoute: typeof ElectionsRoute
    }
    '/candidates/apply': {
      id: '/candidates/apply'
      path: '/apply'
      fullPath: '/candidates/apply'
      preLoaderRoute: typeof CandidatesApplyRouteImport
      parentRoute: typeof CandidatesRoute
    }
    '/elections/candidates/$positionId': {
      id: '/elections/candidates/$positionId'
      path: '/candidates/$positionId'
      fullPath: '/elections/candidates/$positionId'
      preLoaderRoute: typeof ElectionsCandidatesPositionIdRouteImport
      parentRoute: typeof ElectionsRoute
    }
    '/candidates/$candidateId/dashboard': {
      id: '/candidates/$candidateId/dashboard'
      path: '/$candidateId/dashboard'
      fullPath: '/candidates/$candidateId/dashboard'
      preLoaderRoute: typeof CandidatesCandidateIdDashboardRouteImport
      parentRoute: typeof CandidatesRoute
    }
    '/candidates/$candidateId/certificate': {
      id: '/candidates/$candidateId/certificate'
      path: '/$candidateId/certificate'
      fullPath: '/candidates/$candidateId/certificate'
      preLoaderRoute: typeof CandidatesCandidateIdCertificateRouteImport
      parentRoute: typeof CandidatesRoute
    }
  }
}

interface CandidatesRouteChildren {
  CandidatesApplyRoute: typeof CandidatesApplyRoute
  CandidatesCandidateIdCertificateRoute: typeof CandidatesCandidateIdCertificateRoute
  CandidatesCandidateIdDashboardRoute: typeof CandidatesCandidateIdDashboardRoute
}

const CandidatesRouteChildren: CandidatesRouteChildren = {
  CandidatesApplyRoute: CandidatesApplyRoute,
  CandidatesCandidateIdCertificateRoute: CandidatesCandidateIdCertificateRoute,
  CandidatesCandidateIdDashboardRoute: CandidatesCandidateIdDashboardRoute,
}

const CandidatesRouteWithChildren = CandidatesRoute._addFileChildren(
  CandidatesRouteChildren,
)

interface ElectionsRouteChildren {
  ElectionsPositionIdRoute: typeof ElectionsPositionIdRoute
  ElectionsCandidatesPositionIdRoute: typeof ElectionsCandidatesPositionIdRoute
}

const ElectionsRouteChildren: ElectionsRouteChildren = {
  ElectionsPositionIdRoute: ElectionsPositionIdRoute,
  ElectionsCandidatesPositionIdRoute: ElectionsCandidatesPositionIdRoute,
}

const ElectionsRouteWithChildren = ElectionsRoute._addFileChildren(
  ElectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CandidatesRoute: CandidatesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ElectionsRoute: ElectionsRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
