/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ElectionsRouteImport } from './routes/elections'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ElectionsIndexRouteImport } from './routes/elections.index'
import { Route as CandidatesIndexRouteImport } from './routes/candidates.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VerifyCertificateNumberRouteImport } from './routes/verify.$certificateNumber'
import { Route as ReceiptReceiptCodeRouteImport } from './routes/receipt.$receiptCode'
import { Route as ElectionsPositionIdRouteImport } from './routes/elections.$positionId'
import { Route as CandidatesApplyRouteImport } from './routes/candidates.apply'
import { Route as AdminVotersRouteImport } from './routes/admin/voters'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminScheduleRouteImport } from './routes/admin/schedule'
import { Route as AdminPositionsRouteImport } from './routes/admin/positions'
import { Route as AdminNotAuthorizedRouteImport } from './routes/admin/not-authorized'
import { Route as AdminMfaRequiredRouteImport } from './routes/admin/mfa-required'
import { Route as AdminCandidatesRouteImport } from './routes/admin/candidates'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as ElectionsCandidatesPositionIdRouteImport } from './routes/elections.candidates.$positionId'
import { Route as CandidatesCandidateIdDashboardRouteImport } from './routes/candidates.$candidateId.dashboard'
import { Route as CandidatesCandidateIdCertificateRouteImport } from './routes/candidates.$candidateId.certificate'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionsRoute = ElectionsRouteImport.update({
  id: '/elections',
  path: '/elections',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionsIndexRoute = ElectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ElectionsRoute,
} as any)
const CandidatesIndexRoute = CandidatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CandidatesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertificateNumberRoute = VerifyCertificateNumberRouteImport.update({
  id: '/verify/$certificateNumber',
  path: '/verify/$certificateNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptReceiptCodeRoute = ReceiptReceiptCodeRouteImport.update({
  id: '/receipt/$receiptCode',
  path: '/receipt/$receiptCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionsPositionIdRoute = ElectionsPositionIdRouteImport.update({
  id: '/$positionId',
  path: '/$positionId',
  getParentRoute: () => ElectionsRoute,
} as any)
const CandidatesApplyRoute = CandidatesApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => CandidatesRoute,
} as any)
const AdminVotersRoute = AdminVotersRouteImport.update({
  id: '/admin/voters',
  path: '/admin/voters',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/admin/schedule',
  path: '/admin/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPositionsRoute = AdminPositionsRouteImport.update({
  id: '/admin/positions',
  path: '/admin/positions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotAuthorizedRoute = AdminNotAuthorizedRouteImport.update({
  id: '/admin/not-authorized',
  path: '/admin/not-authorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMfaRequiredRoute = AdminMfaRequiredRouteImport.update({
  id: '/admin/mfa-required',
  path: '/admin/mfa-required',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/admin/candidates',
  path: '/admin/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionsCandidatesPositionIdRoute =
  ElectionsCandidatesPositionIdRouteImport.update({
    id: '/candidates/$positionId',
    path: '/candidates/$positionId',
    getParentRoute: () => ElectionsRoute,
  } as any)
const CandidatesCandidateIdDashboardRoute =
  CandidatesCandidateIdDashboardRouteImport.update({
    id: '/$candidateId/dashboard',
    path: '/$candidateId/dashboard',
    getParentRoute: () => CandidatesRoute,
  } as any)
const CandidatesCandidateIdCertificateRoute =
  CandidatesCandidateIdCertificateRouteImport.update({
    id: '/$candidateId/certificate',
    path: '/$candidateId/certificate',
    getParentRoute: () => CandidatesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/candidates': typeof CandidatesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/elections': typeof ElectionsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/mfa-required': typeof AdminMfaRequiredRoute
  '/admin/not-authorized': typeof AdminNotAuthorizedRoute
  '/admin/positions': typeof AdminPositionsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/voters': typeof AdminVotersRoute
  '/candidates/apply': typeof CandidatesApplyRoute
  '/elections/$positionId': typeof ElectionsPositionIdRoute
  '/receipt/$receiptCode': typeof ReceiptReceiptCodeRoute
  '/verify/$certificateNumber': typeof VerifyCertificateNumberRoute
  '/admin/': typeof AdminIndexRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/elections/': typeof ElectionsIndexRoute
  '/candidates/$candidateId/certificate': typeof CandidatesCandidateIdCertificateRoute
  '/candidates/$candidateId/dashboard': typeof CandidatesCandidateIdDashboardRoute
  '/elections/candidates/$positionId': typeof ElectionsCandidatesPositionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/mfa-required': typeof AdminMfaRequiredRoute
  '/admin/not-authorized': typeof AdminNotAuthorizedRoute
  '/admin/positions': typeof AdminPositionsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/voters': typeof AdminVotersRoute
  '/candidates/apply': typeof CandidatesApplyRoute
  '/elections/$positionId': typeof ElectionsPositionIdRoute
  '/receipt/$receiptCode': typeof ReceiptReceiptCodeRoute
  '/verify/$certificateNumber': typeof VerifyCertificateNumberRoute
  '/admin': typeof AdminIndexRoute
  '/candidates': typeof CandidatesIndexRoute
  '/elections': typeof ElectionsIndexRoute
  '/candidates/$candidateId/certificate': typeof CandidatesCandidateIdCertificateRoute
  '/candidates/$candidateId/dashboard': typeof CandidatesCandidateIdDashboardRoute
  '/elections/candidates/$positionId': typeof ElectionsCandidatesPositionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/candidates': typeof CandidatesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/elections': typeof ElectionsRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/mfa-required': typeof AdminMfaRequiredRoute
  '/admin/not-authorized': typeof AdminNotAuthorizedRoute
  '/admin/positions': typeof AdminPositionsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/voters': typeof AdminVotersRoute
  '/candidates/apply': typeof CandidatesApplyRoute
  '/elections/$positionId': typeof ElectionsPositionIdRoute
  '/receipt/$receiptCode': typeof ReceiptReceiptCodeRoute
  '/verify/$certificateNumber': typeof VerifyCertificateNumberRoute
  '/admin/': typeof AdminIndexRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/elections/': typeof ElectionsIndexRoute
  '/candidates/$candidateId/certificate': typeof CandidatesCandidateIdCertificateRoute
  '/candidates/$candidateId/dashboard': typeof CandidatesCandidateIdDashboardRoute
  '/elections/candidates/$positionId': typeof ElectionsCandidatesPositionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/candidates'
    | '/dashboard'
    | '/elections'
    | '/projects'
    | '/register'
    | '/sitemap.xml'
    | '/admin/audit'
    | '/admin/candidates'
    | '/admin/mfa-required'
    | '/admin/not-authorized'
    | '/admin/positions'
    | '/admin/schedule'
    | '/admin/support'
    | '/admin/users'
    | '/admin/voters'
    | '/candidates/apply'
    | '/elections/$positionId'
    | '/receipt/$receiptCode'
    | '/verify/$certificateNumber'
    | '/admin/'
    | '/candidates/'
    | '/elections/'
    | '/candidates/$candidateId/certificate'
    | '/candidates/$candidateId/dashboard'
    | '/elections/candidates/$positionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/projects'
    | '/register'
    | '/sitemap.xml'
    | '/admin/audit'
    | '/admin/candidates'
    | '/admin/mfa-required'
    | '/admin/not-authorized'
    | '/admin/positions'
    | '/admin/schedule'
    | '/admin/support'
    | '/admin/users'
    | '/admin/voters'
    | '/candidates/apply'
    | '/elections/$positionId'
    | '/receipt/$receiptCode'
    | '/verify/$certificateNumber'
    | '/admin'
    | '/candidates'
    | '/elections'
    | '/candidates/$candidateId/certificate'
    | '/candidates/$candidateId/dashboard'
    | '/elections/candidates/$positionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/candidates'
    | '/dashboard'
    | '/elections'
    | '/projects'
    | '/register'
    | '/sitemap.xml'
    | '/admin/audit'
    | '/admin/candidates'
    | '/admin/mfa-required'
    | '/admin/not-authorized'
    | '/admin/positions'
    | '/admin/schedule'
    | '/admin/support'
    | '/admin/users'
    | '/admin/voters'
    | '/candidates/apply'
    | '/elections/$positionId'
    | '/receipt/$receiptCode'
    | '/verify/$certificateNumber'
    | '/admin/'
    | '/candidates/'
    | '/elections/'
    | '/candidates/$candidateId/certificate'
    | '/candidates/$candidateId/dashboard'
    | '/elections/candidates/$positionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CandidatesRoute: typeof CandidatesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ElectionsRoute: typeof ElectionsRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminMfaRequiredRoute: typeof AdminMfaRequiredRoute
  AdminNotAuthorizedRoute: typeof AdminNotAuthorizedRoute
  AdminPositionsRoute: typeof AdminPositionsRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVotersRoute: typeof AdminVotersRoute
  ReceiptReceiptCodeRoute: typeof ReceiptReceiptCodeRoute
  VerifyCertificateNumberRoute: typeof VerifyCertificateNumberRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elections': {
      id: '/elections'
      path: '/elections'
      fullPath: '/elections'
      preLoaderRoute: typeof ElectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elections/': {
      id: '/elections/'
      path: '/'
      fullPath: '/elections/'
      preLoaderRoute: typeof ElectionsIndexRouteImport
      parentRoute: typeof ElectionsRoute
    }
    '/candidates/': {
      id: '/candidates/'
      path: '/'
      fullPath: '/candidates/'
      preLoaderRoute: typeof CandidatesIndexRouteImport
      parentRoute: typeof CandidatesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$certificateNumber': {
      id: '/verify/$certificateNumber'
      path: '/verify/$certificateNumber'
      fullPath: '/verify/$certificateNumber'
      preLoaderRoute: typeof VerifyCertificateNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$receiptCode': {
      id: '/receipt/$receiptCode'
      path: '/receipt/$receiptCode'
      fullPath: '/receipt/$receiptCode'
      preLoaderRoute: typeof ReceiptReceiptCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elections/$positionId': {
      id: '/elections/$positionId'
      path: '/$positionId'
      fullPath: '/elections/$positionId'
      preLoaderRoute: typeof ElectionsPositionIdRouteImport
      parentRoute: typeof ElectionsRoute
    }
    '/candidates/apply': {
      id: '/candidates/apply'
      path: '/apply'
      fullPath: '/candidates/apply'
      preLoaderRoute: typeof CandidatesApplyRouteImport
      parentRoute: typeof CandidatesRoute
    }
    '/admin/voters': {
      id: '/admin/voters'
      path: '/admin/voters'
      fullPath: '/admin/voters'
      preLoaderRoute: typeof AdminVotersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/admin/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/positions': {
      id: '/admin/positions'
      path: '/admin/positions'
      fullPath: '/admin/positions'
      preLoaderRoute: typeof AdminPositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/not-authorized': {
      id: '/admin/not-authorized'
      path: '/admin/not-authorized'
      fullPath: '/admin/not-authorized'
      preLoaderRoute: typeof AdminNotAuthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mfa-required': {
      id: '/admin/mfa-required'
      path: '/admin/mfa-required'
      fullPath: '/admin/mfa-required'
      preLoaderRoute: typeof AdminMfaRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/admin/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elections/candidates/$positionId': {
      id: '/elections/candidates/$positionId'
      path: '/candidates/$positionId'
      fullPath: '/elections/candidates/$positionId'
      preLoaderRoute: typeof ElectionsCandidatesPositionIdRouteImport
      parentRoute: typeof ElectionsRoute
    }
    '/candidates/$candidateId/dashboard': {
      id: '/candidates/$candidateId/dashboard'
      path: '/$candidateId/dashboard'
      fullPath: '/candidates/$candidateId/dashboard'
      preLoaderRoute: typeof CandidatesCandidateIdDashboardRouteImport
      parentRoute: typeof CandidatesRoute
    }
    '/candidates/$candidateId/certificate': {
      id: '/candidates/$candidateId/certificate'
      path: '/$candidateId/certificate'
      fullPath: '/candidates/$candidateId/certificate'
      preLoaderRoute: typeof CandidatesCandidateIdCertificateRouteImport
      parentRoute: typeof CandidatesRoute
    }
  }
}

interface CandidatesRouteChildren {
  CandidatesApplyRoute: typeof CandidatesApplyRoute
  CandidatesIndexRoute: typeof CandidatesIndexRoute
  CandidatesCandidateIdCertificateRoute: typeof CandidatesCandidateIdCertificateRoute
  CandidatesCandidateIdDashboardRoute: typeof CandidatesCandidateIdDashboardRoute
}

const CandidatesRouteChildren: CandidatesRouteChildren = {
  CandidatesApplyRoute: CandidatesApplyRoute,
  CandidatesIndexRoute: CandidatesIndexRoute,
  CandidatesCandidateIdCertificateRoute: CandidatesCandidateIdCertificateRoute,
  CandidatesCandidateIdDashboardRoute: CandidatesCandidateIdDashboardRoute,
}

const CandidatesRouteWithChildren = CandidatesRoute._addFileChildren(
  CandidatesRouteChildren,
)

interface ElectionsRouteChildren {
  ElectionsPositionIdRoute: typeof ElectionsPositionIdRoute
  ElectionsIndexRoute: typeof ElectionsIndexRoute
  ElectionsCandidatesPositionIdRoute: typeof ElectionsCandidatesPositionIdRoute
}

const ElectionsRouteChildren: ElectionsRouteChildren = {
  ElectionsPositionIdRoute: ElectionsPositionIdRoute,
  ElectionsIndexRoute: ElectionsIndexRoute,
  ElectionsCandidatesPositionIdRoute: ElectionsCandidatesPositionIdRoute,
}

const ElectionsRouteWithChildren = ElectionsRoute._addFileChildren(
  ElectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CandidatesRoute: CandidatesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ElectionsRoute: ElectionsRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminMfaRequiredRoute: AdminMfaRequiredRoute,
  AdminNotAuthorizedRoute: AdminNotAuthorizedRoute,
  AdminPositionsRoute: AdminPositionsRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVotersRoute: AdminVotersRoute,
  ReceiptReceiptCodeRoute: ReceiptReceiptCodeRoute,
  VerifyCertificateNumberRoute: VerifyCertificateNumberRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
